version: '3.7'
services:

  # use this for ad-hoc access to the environment from a terminal
  environment:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: ENVIRONMENT
    image: ghcr.io/klagan/sample/dotnet/environment:5.0
    container_name: net5-sample-environment
    restart: "no"
    volumes:
      - type: bind
        source: .
        target: /source
      - type: bind
        source: ${HOME}/.nuget
        target: /home/vscode/.nuget
    user: vscode
    environment:
    - DOCKER_BUILDKIT=1

  # use this to build, run or pack the application
  runner:
    build:
      context: .
      dockerfile: build/Dockerfile
      target: final
      args: 
        DOTNET_SOLUTION: Samples.Sample.sln
    image: ghcr.io/klagan/sample/dotnet/runner:5.0
    container_name: net5-sample-runner
    restart: "no"
    ports: 
      - 8000:5000 # sometimes port 5000 is taken, so use a different port.  here I changed to 8000
      - 5001:5001
    environment:
    - DOCKER_BUILDKIT=1