version: '3.7'

services:

  fpman.co.uk:
    image: ghost:4-alpine
    container_name: fpman.co.uk
    restart: 'no'
    # disable ports when proxy introduced
    ports:
      - 3050:2368

  fpman.uk:
    image: ghost:4-alpine
    container_name: fpman.uk
    restart: 'no'
    ports:
      - 3051:2368