version: '3.7'
services:

  mywebapi:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NUGET_UID
      #   - NUGET_PWD
    image: ghcr.io/klagan/sample/webapi:1.0
    container_name: mywebapi
    restart: "no"
    ports:
      - 5000:5000
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/index.html || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # volumes:
    #    - type: bind
    #      source: ./override
    #      target: /app/override
    environment:
    - DOTNET_USE_POLLING_FILE_WATCHER=true
    - ASPNETCORE_ENVIRONMENT=Development
    - DOCKER_IMAGE_VERSION=local image

  # enable to run
  # myredoc:
  #   image: redocly/redoc
  #   container_name: myredoc
  #   network_mode: host
  #   restart: "no"
  #   # ports are ignored when we set the network to host
  #   environment:
  #     - SPEC_URL=http://localhost:5000/swagger/v1/swagger.yaml
  #     # kebab casing
  #     # ref: https://github.com/Redocly/redoc#redoc-theme-object
  #     # ref: https://stackoverflow.com/questions/52763862/how-to-add-option-in-redoc
  #     - REDOC_OPTIONS=hide-download-button disable-search
 